### ISSUE TITLE
API v2 Deprecated and shut down :(

### ISSUE THREAD

**Issue by davidbreetzke** [bubbl/SimpleGoogleAlarmClock#3]
The Google Calendar API v2 was shut down on November 17 2014
https://developers.google.com/google-apps/calendar/v2/developers_guide_protocol

I would really like to use your app, but it doesn't work for me. It just hangs on the CalendarQuery.

Would you consider migrating this app to the the API v3
https://developers.google.com/google-apps/calendar/migration

**Comment by bubbl** [comment]
Feel free to fork it and update
